-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 0b70e285e369bcb24b57b74929490ea7be9c4b19
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/asottile/reorder_python_imports
    sha: 46f0b4b5d15f8405c0c70d071f25f50ac3965909
    hooks:
    -   id: reorder-python-imports
